# Generated by Django 6.0.4 on 2026-05-27 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sample',
            options={},
        ),
        migrations.RemoveField(
            model_name='historicalsample',
            name='order',
        ),
        migrations.RemoveField(
            model_name='historicalsamplingplan',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='order',
        ),
        migrations.RemoveField(
            model_name='samplingplan',
            name='description',
        ),
        migrations.AddField(
            model_name='historicalsamplingplan',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Sample Plan Name'),
        ),
        migrations.AddField(
            model_name='samplingplan',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Sample Plan Name'),
        ),
        migrations.AlterField(
            model_name='samplingplan',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sampling_plans', to='production.step', verbose_name='Related Step'),
        ),
    ]
