# Generated by Django 6.0.4 on 2026-05-07 08:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_step'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('format_type', models.CharField(choices=[('numeric', 'Numeric'), ('text', 'Text/Comment'), ('bool', 'Yes/No')], default='numeric', max_length=20)),
                ('format_low_range', models.FloatField(blank=True, null=True)),
                ('format_high_range', models.FloatField(blank=True, null=True)),
                ('low_proven_acceptable_range', models.FloatField(blank=True, null=True)),
                ('high_proven_acceptable_range', models.FloatField(blank=True, null=True)),
                ('low_normal_operating_range', models.FloatField(blank=True, null=True)),
                ('high_normal_operating_range', models.FloatField(blank=True, null=True)),
                ('order', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='production.step')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('step', 'order')},
            },
        ),
    ]
