# Generated by Django 6.0.4 on 2026-05-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_sample_options_remove_historicalsample_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsamplingplan',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='samplingplan',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
