# Generated by Django 6.0.4 on 2026-06-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_alter_historicalsamplingplan_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsample',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
