# Generated by Django 6.0.4 on 2026-06-01 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_historicalsample_unit_sample_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsample',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='unit',
        ),
    ]
