# Generated by Django 6.0.4 on 2026-05-18 08:09

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_parameter_rejection_reason_parameter_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalparameter',
            name='format_high_range',
            field=models.FloatField(blank=True, null=True, verbose_name='Format High Range'),
        ),
        migrations.AlterField(
            model_name='historicalparameter',
            name='format_low_range',
            field=models.FloatField(blank=True, null=True, verbose_name='Format Low Range'),
        ),
        migrations.AlterField(
            model_name='historicalparameter',
            name='format_type',
            field=models.CharField(choices=[('numeric', 'Numeric'), ('text', 'Text/Comment'), ('bool', 'Yes/No')], default='numeric', max_length=20, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='historicalparameter',
            name='high_normal_operating_range',
            field=models.FloatField(blank=True, null=True, verbose_name='NOR High'),
        ),
        migrations.AlterField(
            model_name='historicalparameter',
            name='high_proven_acceptable_range',
            field=models.FloatField(blank=True, null=True, verbose_name='PAR High'),
        ),
        migrations.AlterField(
            model_name='historicalparameter',
            name='low_normal_operating_range',
            field=models.FloatField(blank=True, null=True, verbose_name='NOR Low'),
        ),
        migrations.AlterField(
            model_name='historicalparameter',
            name='low_proven_acceptable_range',
            field=models.FloatField(blank=True, null=True, verbose_name='PAR Low'),
        ),
        migrations.AlterField(
            model_name='historicalparameter',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Parameter Name'),
        ),
        migrations.AlterField(
            model_name='historicalparameter',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Order in Step'),
        ),
        migrations.AlterField(
            model_name='historicalparameter',
            name='step',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.step', verbose_name='Related Step'),
        ),
        migrations.AlterField(
            model_name='historicalparameter',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='historicalprocess',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Process Name'),
        ),
        migrations.AlterField(
            model_name='historicalstep',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Order in Unit'),
        ),
        migrations.AlterField(
            model_name='historicalstep',
            name='unit_operation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.unitoperation', verbose_name='Unit Operation'),
        ),
        migrations.AlterField(
            model_name='historicalunitoperation',
            name='unit_type',
            field=models.CharField(choices=[('USP', 'USP (Upstream Processing)'), ('DSP', 'DSP (Downstream Processing)')], max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='format_high_range',
            field=models.FloatField(blank=True, null=True, verbose_name='Format High Range'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='format_low_range',
            field=models.FloatField(blank=True, null=True, verbose_name='Format Low Range'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='format_type',
            field=models.CharField(choices=[('numeric', 'Numeric'), ('text', 'Text/Comment'), ('bool', 'Yes/No')], default='numeric', max_length=20, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='high_normal_operating_range',
            field=models.FloatField(blank=True, null=True, verbose_name='NOR High'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='high_proven_acceptable_range',
            field=models.FloatField(blank=True, null=True, verbose_name='PAR High'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='low_normal_operating_range',
            field=models.FloatField(blank=True, null=True, verbose_name='NOR Low'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='low_proven_acceptable_range',
            field=models.FloatField(blank=True, null=True, verbose_name='PAR Low'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Parameter Name'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Order in Step'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='production.step', verbose_name='Related Step'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='process',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Process Name'),
        ),
        migrations.AlterField(
            model_name='step',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Order in Unit'),
        ),
        migrations.AlterField(
            model_name='step',
            name='unit_operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='production.unitoperation', verbose_name='Unit Operation'),
        ),
        migrations.AlterField(
            model_name='unitoperation',
            name='unit_type',
            field=models.CharField(choices=[('USP', 'USP (Upstream Processing)'), ('DSP', 'DSP (Downstream Processing)')], max_length=10, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='AnalyticalMethod',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'To validate'), ('VALIDATED', 'Validated'), ('REJECTED', 'Rejected')], default='DRAFT', help_text='Object must be validated first to be used in other relations.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason why this was rejected', null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Method Name')),
                ('volume_required', models.FloatField(verbose_name='Volume Required (mL)')),
                ('storage_temp', models.CharField(max_length=255, verbose_name='Storage Temperature')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalAnalyticalMethod',
            fields=[
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('DRAFT', 'To validate'), ('VALIDATED', 'Validated'), ('REJECTED', 'Rejected')], default='DRAFT', help_text='Object must be validated first to be used in other relations.', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason why this was rejected', null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Method Name')),
                ('volume_required', models.FloatField(verbose_name='Volume Required (mL)')),
                ('storage_temp', models.CharField(max_length=255, verbose_name='Storage Temperature')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical analytical method',
                'verbose_name_plural': 'historical analytical methods',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSample',
            fields=[
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('DRAFT', 'To validate'), ('VALIDATED', 'Validated'), ('REJECTED', 'Rejected')], default='DRAFT', help_text='Object must be validated first to be used in other relations.', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason why this was rejected', null=True)),
                ('sample_name', models.CharField(max_length=255, verbose_name='Sample Name')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('analytical_method', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.analyticalmethod', verbose_name='Analytical Method')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('step', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.step', verbose_name='Step')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical sample',
                'verbose_name_plural': 'historical samples',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'To validate'), ('VALIDATED', 'Validated'), ('REJECTED', 'Rejected')], default='DRAFT', help_text='Object must be validated first to be used in other relations.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason why this was rejected', null=True)),
                ('sample_name', models.CharField(max_length=255, verbose_name='Sample Name')),
                ('analytical_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='production.analyticalmethod', verbose_name='Analytical Method')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='production.step', verbose_name='Step')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
