# Generated by Django 6.0.4 on 2026-06-12 08:56

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_remove_historicalsample_unit_remove_sample_unit'),
        ('referential', '0005_remove_analyticalmethod_format_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplingplan',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='samplingplan',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='samplingplan',
            name='step',
        ),
        migrations.RemoveField(
            model_name='samplingplan',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='historicalsample',
            name='sampling_plan',
        ),
        migrations.AlterModelOptions(
            name='historicalsample',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Sample', 'verbose_name_plural': 'historical Samples'},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ['name'], 'verbose_name': 'Sample'},
        ),
        migrations.AlterUniqueTogether(
            name='sample',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='historicalsample',
            name='analytical_method',
        ),
        migrations.RemoveField(
            model_name='historicalsample',
            name='sample_name',
        ),
        migrations.AddField(
            model_name='historicalsample',
            name='name',
            field=models.CharField(default='old', max_length=255, verbose_name='Sample Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalsample',
            name='step',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.step', verbose_name='Related Step'),
        ),
        migrations.AddField(
            model_name='sample',
            name='name',
            field=models.CharField(default='non', max_length=255, verbose_name='Sample Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
            name='step',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='production.step', verbose_name='Related Step'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('analysis_name', models.CharField(max_length=25, verbose_name='Analysis Name')),
                ('analytical_method', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='analyses', to='referential.analyticalmethod', verbose_name='Analytical Method')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='production.sample', verbose_name='Related Sample')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analysis',
                'verbose_name_plural': 'Analyses',
                'unique_together': {('sample', 'analysis_name', 'analytical_method')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalAnalysis',
            fields=[
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('analysis_name', models.CharField(max_length=25, verbose_name='Analysis Name')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('analytical_method', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='referential.analyticalmethod', verbose_name='Analytical Method')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.sample', verbose_name='Related Sample')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Analysis',
                'verbose_name_plural': 'historical Analyses',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.DeleteModel(
            name='HistoricalSamplingPlan',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='analytical_method',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='sample_name',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='sampling_plan',
        ),
        migrations.DeleteModel(
            name='SamplingPlan',
        ),
    ]
