# Generated by Django 6.0.4 on 2026-05-19 07:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_remove_sample_analytical_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'ordering': ['code', '-version']},
        ),
        migrations.RemoveField(
            model_name='unitoperation',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='unitoperation',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='unitoperation',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='unitoperation',
            name='status',
        ),
        migrations.AddField(
            model_name='historicalprocess',
            name='parent_version',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.process'),
        ),
        migrations.AddField(
            model_name='historicalprocess',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Version'),
        ),
        migrations.AddField(
            model_name='process',
            name='parent_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='production.process'),
        ),
        migrations.AddField(
            model_name='process',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='historicalprocess',
            name='code',
            field=models.CharField(max_length=100, verbose_name='Process Code'),
        ),
        migrations.AlterField(
            model_name='historicalprocess',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'To Validate'), ('VALIDATED', 'Validated'), ('REJECTED', 'Needs Correction')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='process',
            name='code',
            field=models.CharField(max_length=100, verbose_name='Process Code'),
        ),
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'To Validate'), ('VALIDATED', 'Validated'), ('REJECTED', 'Needs Correction')], default='DRAFT', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='process',
            unique_together={('code', 'version')},
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, verbose_name='Step Name')),
                ('order', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('unit_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='production.unitoperation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('unit_operation', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('format_type', models.CharField(choices=[('numeric', 'Numeric'), ('text', 'Text/Comment'), ('bool', 'Yes/No')], default='numeric', max_length=20)),
                ('format_low_range', models.FloatField(blank=True, null=True)),
                ('format_high_range', models.FloatField(blank=True, null=True)),
                ('low_proven_acceptable_range', models.FloatField(blank=True, null=True)),
                ('high_proven_acceptable_range', models.FloatField(blank=True, null=True)),
                ('low_normal_operating_range', models.FloatField(blank=True, null=True)),
                ('high_normal_operating_range', models.FloatField(blank=True, null=True)),
                ('order', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='production.step')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('step', 'order')},
            },
        ),
        migrations.DeleteModel(
            name='HistoricalUnitOperation',
        ),
    ]
