# Generated by Django 6.0.4 on 2026-06-12 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_remove_samplingplan_created_by_and_more'),
        ('referential', '0005_remove_analyticalmethod_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='analytical_method',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'status': 'VALIDATED'}, on_delete=django.db.models.deletion.PROTECT, related_name='analyses', to='referential.analyticalmethod', verbose_name='Analytical Method'),
        ),
        migrations.AlterField(
            model_name='historicalanalysis',
            name='analytical_method',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'is_active': True, 'status': 'VALIDATED'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='referential.analyticalmethod', verbose_name='Analytical Method'),
        ),
    ]
