# Generated by Django 6.0.4 on 2026-06-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_alter_analysis_analytical_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalparameter',
            name='format_high_range',
            field=models.FloatField(blank=True, null=True, verbose_name='Format High Range'),
        ),
        migrations.AlterField(
            model_name='historicalparameter',
            name='format_low_range',
            field=models.FloatField(blank=True, null=True, verbose_name='Format Low Range'),
        ),
        migrations.AlterField(
            model_name='historicalparameter',
            name='unit',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parameter',
            name='format_high_range',
            field=models.FloatField(blank=True, null=True, verbose_name='Format High Range'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='format_low_range',
            field=models.FloatField(blank=True, null=True, verbose_name='Format Low Range'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='unit',
            field=models.CharField(max_length=50),
        ),
    ]
