# Generated by Django 6.0.4 on 2026-06-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_alter_historicalparameter_format_high_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='format_high_range',
            field=models.FloatField(blank=True, null=True, verbose_name='Validation High Range'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='format_low_range',
            field=models.FloatField(blank=True, null=True, verbose_name='Validation Low Range'),
        ),
        migrations.AddField(
            model_name='historicalanalysis',
            name='format_high_range',
            field=models.FloatField(blank=True, null=True, verbose_name='Validation High Range'),
        ),
        migrations.AddField(
            model_name='historicalanalysis',
            name='format_low_range',
            field=models.FloatField(blank=True, null=True, verbose_name='Validation Low Range'),
        ),
    ]
