# Generated by Django 6.0.6 on 2026-06-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_analysis_format_high_range_analysis_format_low_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='high_normal_operating_range',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='low_normal_operating_range',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalanalysis',
            name='high_normal_operating_range',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalanalysis',
            name='low_normal_operating_range',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
