# Generated by Django 6.0.6 on 2026-07-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_analysis_high_normal_operating_range_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='format_low_range',
            new_name='format_lower_range',
        ),
        migrations.RenameField(
            model_name='analysis',
            old_name='format_high_range',
            new_name='format_upper_range',
        ),
        migrations.RenameField(
            model_name='analysis',
            old_name='low_normal_operating_range',
            new_name='lower_normal_operating_range',
        ),
        migrations.RenameField(
            model_name='analysis',
            old_name='high_normal_operating_range',
            new_name='upper_normal_operating_range',
        ),
        migrations.RenameField(
            model_name='historicalanalysis',
            old_name='format_low_range',
            new_name='format_lower_range',
        ),
        migrations.RenameField(
            model_name='historicalanalysis',
            old_name='format_high_range',
            new_name='format_upper_range',
        ),
        migrations.RenameField(
            model_name='historicalanalysis',
            old_name='low_normal_operating_range',
            new_name='lower_normal_operating_range',
        ),
        migrations.RenameField(
            model_name='historicalanalysis',
            old_name='high_normal_operating_range',
            new_name='upper_normal_operating_range',
        ),
        migrations.RenameField(
            model_name='historicalparameter',
            old_name='format_low_range',
            new_name='format_lower_range',
        ),
        migrations.RenameField(
            model_name='historicalparameter',
            old_name='format_high_range',
            new_name='format_upper_range',
        ),
        migrations.RenameField(
            model_name='historicalparameter',
            old_name='low_normal_operating_range',
            new_name='lower_normal_operating_range',
        ),
        migrations.RenameField(
            model_name='historicalparameter',
            old_name='high_normal_operating_range',
            new_name='upper_normal_operating_range',
        ),
        migrations.RenameField(
            model_name='historicalparameter',
            old_name='low_proven_acceptable_range',
            new_name='lower_proven_acceptable_range',
        ),
        migrations.RenameField(
            model_name='historicalparameter',
            old_name='high_proven_acceptable_range',
            new_name='upper_proven_acceptable_range',
        ),
        migrations.RenameField(
            model_name='parameter',
            old_name='format_low_range',
            new_name='format_lower_range',
        ),
        migrations.RenameField(
            model_name='parameter',
            old_name='format_high_range',
            new_name='format_upper_range',
        ),
        migrations.RenameField(
            model_name='parameter',
            old_name='low_normal_operating_range',
            new_name='lower_normal_operating_range',
        ),
        migrations.RenameField(
            model_name='parameter',
            old_name='high_normal_operating_range',
            new_name='upper_normal_operating_range',
        ),
        migrations.RenameField(
            model_name='parameter',
            old_name='low_proven_acceptable_range',
            new_name='lower_proven_acceptable_range',
        ),
        migrations.RenameField(
            model_name='parameter',
            old_name='high_proven_acceptable_range',
            new_name='upper_proven_acceptable_range',
        ),
        migrations.AlterField(
            model_name='analysis',
            name='format_lower_range',
            field=models.FloatField(blank=True, null=True, verbose_name='Allowed Measurement Lower Range'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='format_upper_range',
            field=models.FloatField(blank=True, null=True, verbose_name='Allowed Measurement Upper Range'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='format_lower_range',
            field=models.FloatField(blank=True, null=True, verbose_name='Allowed Measurement Lower Range'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='format_upper_range',
            field=models.FloatField(blank=True, null=True, verbose_name='Allowed Measurement Upper Range'),
        ),
    ]
