# Generated by Django 6.0.4 on 2026-05-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_historicalsample_sample'),
        ('referential', '0009_analyticalmethod_historicalanalyticalmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='analytical_methods',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, related_name='samples', to='referential.analyticalmethod', verbose_name='Analytical Methods'),
        ),
    ]
