# Generated by Django 6.0.6 on 2026-07-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_rename_parameter_and_analysis_ranges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalanalysis',
            name='format_lower_range',
            field=models.FloatField(blank=True, null=True, verbose_name='Allowed Measurement Lower Range'),
        ),
        migrations.AlterField(
            model_name='historicalanalysis',
            name='format_upper_range',
            field=models.FloatField(blank=True, null=True, verbose_name='Allowed Measurement Upper Range'),
        ),
        migrations.AlterField(
            model_name='historicalparameter',
            name='format_lower_range',
            field=models.FloatField(blank=True, null=True, verbose_name='Allowed Measurement Lower Range'),
        ),
        migrations.AlterField(
            model_name='historicalparameter',
            name='format_upper_range',
            field=models.FloatField(blank=True, null=True, verbose_name='Allowed Measurement Upper Range'),
        ),
    ]
