# Generated by Django 6.0.4 on 2026-05-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='name',
            field=models.CharField(default='test', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalbatch',
            name='name',
            field=models.CharField(db_index=True, default='test', max_length=100),
            preserve_default=False,
        ),
    ]
