# Generated by Django 6.0.4 on 2026-06-01 06:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0004_historicalparameterresult_historicalsampleresult_and_more'),
        ('production', '0003_alter_historicalsamplingplan_name_and_more'),
        ('referential', '0004_alter_globalunitoperation_unit_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='batch_status',
        ),
        migrations.RemoveField(
            model_name='historicalbatch',
            name='batch_status',
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('project', 'process', 'iteration_number'), name='unique_active_iteration_per_project_process'),
        ),
    ]
