# Generated by Django 6.0.4 on 2026-06-12 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0005_remove_batch_batch_status_and_more'),
        ('production', '0006_remove_samplingplan_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsampleresult',
            name='sample',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.analysis', verbose_name='Process Sample'),
        ),
        migrations.AlterField(
            model_name='sampleresult',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='production.analysis', verbose_name='Process Sample'),
        ),
    ]
