# Generated by Django 6.0.4 on 2026-06-12 12:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0006_alter_historicalsampleresult_sample_and_more'),
        ('production', '0006_remove_samplingplan_created_by_and_more'),
        ('referential', '0005_remove_analyticalmethod_format_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='batch',
            name='unique_active_iteration_per_project_process',
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('project', 'process', 'category', 'iteration_number'), name='unique_active_iteration_per_project_process_category'),
        ),
    ]
