# Generated by Django 6.0.4 on 2026-06-15 09:36

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0007_remove_batch_unique_active_iteration_per_project_process_and_more'),
        ('production', '0009_analysis_format_high_range_analysis_format_low_range_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampleresult',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='sampleresult',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sampleresult',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='sampleresult',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='sampleresult',
            name='updated_by',
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'To validate'), ('VALIDATED', 'Validated'), ('REJECTED', 'Rejected')], default='DRAFT', help_text='Object must be validated first to be used in other relations.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason why this was rejected', null=True)),
                ('actual_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Actual Value')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='production.analysis', verbose_name='Process Analysis')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='batch.batch', verbose_name='Related Batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analysis Result',
                'verbose_name_plural': 'Analysis Results',
            },
        ),
        migrations.CreateModel(
            name='HistoricalAnalysisResult',
            fields=[
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('DRAFT', 'To validate'), ('VALIDATED', 'Validated'), ('REJECTED', 'Rejected')], default='DRAFT', help_text='Object must be validated first to be used in other relations.', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason why this was rejected', null=True)),
                ('actual_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Actual Value')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('analysis', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.analysis', verbose_name='Process Analysis')),
                ('batch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='batch.batch', verbose_name='Related Batch')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Analysis Result',
                'verbose_name_plural': 'historical Analysis Results',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.DeleteModel(
            name='HistoricalSampleResult',
        ),
        migrations.DeleteModel(
            name='SampleResult',
        ),
    ]
