# Generated by Django 6.0.6 on 2026-06-19 08:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0008_remove_sampleresult_batch_and_more'),
        ('production', '0009_analysis_format_high_range_analysis_format_low_range_and_more'),
        ('referential', '0005_remove_analyticalmethod_format_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='batch',
            name='unique_active_iteration_per_project_process_category',
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('project', 'iteration_number'), name='unique_active_iteration_per_project'),
        ),
    ]
