# Generated by Django 6.0.4 on 2026-05-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='start_date',
            field=models.DateField(),
        ),
    ]
