# Generated by Django 6.0.4 on 2026-05-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referential', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticalmethod',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Method Name'),
        ),
        migrations.AlterField(
            model_name='historicalanalyticalmethod',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Method Name'),
        ),
    ]
