# Generated by Django 6.0.4 on 2026-05-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referential', '0003_globalunitoperation_historicalglobalunitoperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalunitoperation',
            name='unit_type',
            field=models.CharField(choices=[('USP', 'USP'), ('DSP', 'DSP')], max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='historicalglobalunitoperation',
            name='unit_type',
            field=models.CharField(choices=[('USP', 'USP'), ('DSP', 'DSP')], max_length=10, verbose_name='Type'),
        ),
    ]
