# Generated by Django 6.0.4 on 2026-06-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referential', '0004_alter_globalunitoperation_unit_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyticalmethod',
            name='format',
        ),
        migrations.RemoveField(
            model_name='historicalanalyticalmethod',
            name='format',
        ),
        migrations.AddField(
            model_name='analyticalmethod',
            name='sop_code',
            field=models.CharField(default='ml', max_length=255, verbose_name='SOP Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analyticalmethod',
            name='sop_version',
            field=models.CharField(default=1, max_length=50, verbose_name='SOP Version'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalanalyticalmethod',
            name='sop_code',
            field=models.CharField(default='1', max_length=255, verbose_name='SOP Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalanalyticalmethod',
            name='sop_version',
            field=models.CharField(default='1', max_length=50, verbose_name='SOP Version'),
            preserve_default=False,
        ),
    ]
