# Generated by Django 6.0.6 on 2026-07-03 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referential', '0005_remove_analyticalmethod_format_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproject',
            name='name',
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('client', 'code')},
        ),
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
    ]
