# Generated by Django 6.0.6 on 2026-07-03 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referential', '0006_remove_historicalproject_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalmoleculetype',
            old_name='name',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='moleculetype',
            old_name='name',
            new_name='type',
        ),
    ]
