# Generated by Django 6.0.4 on 2026-05-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referential', '0007_alter_client_created_at_alter_client_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason why this was rejected', null=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason why this was rejected', null=True),
        ),
        migrations.AddField(
            model_name='historicalmoleculetype',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason why this was rejected', null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason why this was rejected', null=True),
        ),
        migrations.AddField(
            model_name='moleculetype',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason why this was rejected', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason why this was rejected', null=True),
        ),
    ]
